# -*- coding: utf-8 -*-
"""Queue using two Stacks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZ4zGeyvt60krrVvNMIBReKGhkjgEwMW
"""

class Node:

  def __init__(self, value):
    self.data = value
    self.next = None

class Queue:

  def __init__(self):
    self.rear = None
    self.front = None

  def enque(self, value):
    new_node = Node(value)
    new_node.next = self.rear
    self.rear = new_node

  def deque(self):
    if self.front == None:
      while self.rear != None:
        new_node = Node(self.rear.data)
        new_node.next = self.front
        self.front = new_node

        self.rear = self.rear.next

    if self.front == None:
      return 'Queue is empty'

    data = self.front.data
    self.front = self.front.next
    return data

  def __str__(self):
    result = ''
    start = self.front
    while start != None:
      result += str(start.data) + '<-'
      start = start.next
    else:
      result1 = ''
      while self.rear != None:
        result1 = '<-' + str(self.rear.data) + result1
        self.rear = self.rear.next
    return result + result1[2:]

q = Queue()

q.enque(2)
q.enque(4)
q.enque(3)
q.deque()
q.enque(5)
q.enque(6)
q.deque()
print(q)







